name: Django CI 

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DEBUG: ${{ secrets.DEBUG }}
      SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

      EXTERNAL_DATABASE_URL: ${{ secrets.EXTERNAL_DATABASE_URL }}

      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }} 
      EMAIL_POST: ${{ secrets.EMAIL_POST }}
      EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}  
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.7
    - uses: actions/checkout@v2
    - name: Install redis
      run: sudo apt-get install -y redis-server
    - name: Verify that redis is up
      run: redis-cli ping    
    - name: Install Dependencies and Virtual Environment
      run: |
        pip3 install -r requirements.txt
        python -m pip install --upgrade pip 
        python3 -m venv env
        source env/bin/activate
        cd local/
    - name: run database migrations
      env:
          DATABASE_URL: ${{ env.EXTERNAL_DATABASE_URL }}
      run: |
        python3 manage.py migrate
    - name: Coverage report
      env:
        DEBUG: "0"
        SECRET_KEY: ${{ env.SECRET_KEY }}  
        EMAIL_HOST_PASSWORD: ${{ env.EMAIL_HOST_PASSWORD }} 
        EMAIL_POST: ${{ env.EMAIL_POST }}
        EMAIL_USE_TLS: ${{ env.EMAIL_USE_TLS }}
      run: |
        pip install coverage
        coverage run --source='.' manage.py test blog
        coverage report
    - name: Django test
      env:
        DEBUG: "0"
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        EMAIL_HOST_PASSWORD: ${{ env.EMAIL_HOST_PASSWORD }} 
        EMAIL_POST: ${{ env.EMAIL_POST }}
        EMAIL_USE_TLS: ${{ env.EMAIL_USE_TLS }}
      run: |
        python3 manage.py test
